task:
  name: Gradle Tests
  container:
    image: gradle:jdk11
    cpu: 4
    memory: 16G
  gradle_cache:
    folder: ~/.gradle/caches
    reupload_on_changes: true
  check_script: gradle check

task:
  name: Qodana
  container:
    image: jetbrains/qodana:latest
  env:
    CIRRUS_WORKING_DIR: /data/project
  generate_report_script:
    - /opt/idea/bin/entrypoint --save-report --report-dir=report
  always:
    results_artifacts:
      path: "report/results/result-allProblems.json"
      format: qodana
    
    html_report_artifacts:
      path: "report/**.*"

task:
  name: Bazel Tests
  container:
    image: l.gcr.io/google/bazel:latest
    cpu: 4
    memory: 16G
  test_script: bazel test --remote_cache=http://$CIRRUS_HTTP_CACHE_HOST //services/...
